import { DBPendingPrediction } from '@/lib/supabase';

// Shared in-memory storage for when Supabase is not configured
// This is shared between the launch route and like route
export const inMemoryPredictions: DBPendingPrediction[] = [
  {
    id: 'pred-1',
    title: 'Will PEPE hit $10B market cap?',
    description: 'Predicting if PEPE memecoin will reach $10 billion market cap before Q2 2026',
    category: 'crypto',
    resolution_criteria: 'CoinGecko market cap data on the specified date',
    end_date: '2026-06-30T00:00:00.000Z',
    likes: 12,
    created_by: null,
    is_graduated: false,
    graduated_market_id: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
  },
  {
    id: 'pred-2',
    title: 'Ansem tweets 5 times about SOL this week',
    description: 'Will Ansem post at least 5 tweets mentioning SOL/Solana on his main account this week?',
    category: 'kol',
    resolution_criteria: 'Count tweets from @blknoiz06 mentioning SOL/Solana',
    end_date: '2026-01-25T00:00:00.000Z',
    likes: 8,
    created_by: 'Ank8...x9Pz',
    is_graduated: false,
    graduated_market_id: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
  },
  {
    id: 'pred-3',
    title: 'Trump mentions crypto in State of Union',
    description: 'Will Trump mention cryptocurrency, Bitcoin, or blockchain in the 2026 State of the Union address?',
    category: 'politics',
    resolution_criteria: 'Official transcript of the State of the Union address',
    end_date: '2026-03-01T00:00:00.000Z',
    likes: 14,
    created_by: null,
    is_graduated: false,
    graduated_market_id: null,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    image_url: null,
  },
  {
    id: 'pred-4',
    title: 'New AI token launches and 10x in 24h',
    description: 'Will any new AI-related token launched this month achieve 10x gains within 24 hours of launch?',
    category: 'token',
    resolution_criteria: 'DEXScreener data for new AI token launches',
    end_date: '2026-01-31T00:00:00.000Z',
    likes: 5,
    created_by: 'BrX2...m4Kp',
    is_graduated: false,
    graduated_market_id: null,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    image_url: null,
  },
  {
    id: 'pred-5',
    title: 'Chiefs win Super Bowl LX',
    description: 'Will the Kansas City Chiefs win Super Bowl LX?',
    category: 'sports',
    resolution_criteria: 'Official NFL Super Bowl results',
    end_date: '2026-02-10T00:00:00.000Z',
    likes: 3,
    created_by: null,
    is_graduated: false,
    graduated_market_id: null,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    image_url: null,
  },
];

export const inMemoryLikes: Set<string> = new Set(); // "predictionId:userIdentifier"
